# Generated by Django 4.2.6 on 2024-08-27 13:45

import contentflow.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='social/image')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upadated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('thumbnail_title', models.TextField(blank=True, null=True)),
                ('voice_type', models.CharField(choices=[('Human', 'Human'), ('AI', 'AI')], default='Human', max_length=100)),
                ('voice_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Deleted', 'Deleted')], max_length=100)),
                ('content_format', models.CharField(blank=True, choices=[('Long Video', 'Long Video'), ('Post', 'Post'), ('Short', 'Short'), ('Reel', 'Short'), ('Story', 'Story')], default='Post', max_length=100)),
                ('background_music', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('social_media', models.ManyToManyField(to='contentflow.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voice_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentflow.voiceauthor')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=contentflow.models.Profile.get_absolute_url)),
                ('rol', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
