# Generated by Django 4.2.6 on 2024-08-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Deleted', 'Deleted')], default='Created', max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='thumbnail_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
