# Generated by Django 5.1 on 2024-10-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0007_title_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_type',
        ),
    ]
