# Generated by Django 5.1 on 2024-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0008_remove_character_character_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('r', 'Read'), ('u', 'Unread')], default='u', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook', models.TextField()),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
