# Generated by Django 5.1 on 2024-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0009_contact_hook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='channel',
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
