# Generated by Django 5.1 on 2024-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0010_remove_character_channel_character_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, choices=[('stoic', 'Stoic'), ('psycologist', 'Psycologist'), ('writer', 'Writer'), ('mentor', 'Mentor')], max_length=60, null=True),
        ),
    ]
