# Generated by Django 5.1 on 2024-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0011_rename_name_account_platform_alter_character_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='author',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='two_factor_authenticator',
            field=models.CharField(blank=True, choices=[('google_authenticator', 'Google Authenticator'), ('microsoft_athenticator', 'Microsoft Athenticator'), ('email', 'Email'), ('phone', 'Phone')], max_length=200, null=True),
        ),
    ]
