# Generated by Django 5.1 on 2024-11-12 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0012_phrase_author_alter_account_two_factor_authenticator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
