# Generated by Django 5.1 on 2025-04-04 05:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0013_alter_hook_uuid_alter_title_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
