# Generated by Django 5.1 on 2025-04-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentflow', '0014_alter_prompt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(),
        ),
    ]
